name: Block merging main into release branches

on:
  pull_request:
    branches:
      - "all/release/*"

jobs:
  block-merging-main-into-release-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is main
        if: ${{ github.head_ref == 'main' }}
        run: |
          echo "‚ùå Pull requests from 'main' into all/release/* are not allowed."
          exit 1
